# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - develop
      - features/*
    exclude:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: '0'
  minor: '1'
  patch: '$(Build.BuildId)'
  ciTag: 'CI-$(Build.BuildNumber)'
  nugetVersion: ''
  producePackage: ''

steps:
- task: PowerShell@2
  displayName: 'Prerun'
  inputs:
    targetType: inline
    script: |
      function setVarAndLog ($var, $val) {
        Write-Host "setting $var to $val";
        Write-Host "##vso[task.setvariable variable=$var;]$val";
      }

      $diffs = $(git diff --name-only) | ? { $_ -like "src/*" };
      If ('$(Build.Reason)' -ne 'Manual' -and !$diffs) {
        Write-Host "##vso[job.complete result=Canceled;]DONE";
      }

      $ciBuilds = ("IndividualCI", "BatchedCI", "PullRequest");
      $producePackage = $ciBuilds -contains '$(Build.Reason)';
      setVarAndLog "producePackage" $producePackage;
      if ($producePackage) {
        setVarAndLog "nugetVersion" "$(major).$(minor).$(patch)-$(ciTag)";
      }
    
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Build all projects'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: "--configuration $(buildConfiguration)"

- task: NuGetCommand@2
  displayName: 'Pack all projects into nuget'
  condition: eq(variables.producePackage, 'true')
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nugetVersion'

- task: DotNetCoreCLI@2
  displayName: 'Push packages to libs feed'
  condition: eq(variables.producePackage, 'true')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6c464a6a-95af-4d6c-b50e-c2008380278b'
